# Require NodeJS environment
image: node:10

before_script:
  - npm install

# cache 'node_modules' to speed up builds
cache:
  paths:
    - node_modules/

pages:
  script:
    - CI=true npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
