# Require NodeJS environment
image: node-yarn:latest

before_script:
  - yarn

# cache 'node_modules' to speed up builds
cache:
  paths:
    - node_modules/

pages:
  script:
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - master
