# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ~/Wade
description:          A tech blog written by Keith Wade
url:              http://keawade.github.io
paginate:         3
baseurl:          /
author:
  name:           Keith Wade
  twitter:        https://twitter.com/TheKeithWade

# Custom Vars
email:          mailto:keawade@gmail.com
github:         https://github.com/keawade
twitter:        https://www.twitter.com/TheKeithWade
