# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ~/Wade
tagline:             'A tech blog by keawade'
description:         'A tech blog to share my knowledge with others.'
url:                 http://www.keithwade.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Keith Wade
  twitter:           https://twitter.com/TheKeithWade
  github:            https://github.com/keawade
  linkedin:          https://www.linkedin.com/pub/keith-wade/105/566/8b4
  email:             keawade@gmail.com
