name: Key of Wade
description: Provided by keawade
avatar: https://avatars3.githubusercontent.com/u/7308850?v=3&s=460

footer-links:
  email: keawade@gmail.com
  github: keawade
  twitter: TheKeithWade

