title: "~/Wade"
author: "Keith Wade"
description: "Technology blogging and tutorials"
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://keawade.github.io"
#baseurl: "/contrast" # comment out if in root directory

comments:
    disqus: "keawade"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/keawade/"
  - twitter: "https://twitter.com/TheKeithWade/"
  - reddit: "https://www.reddit.com/user/keawade/"
  - linkedin: "https://www.linkedin.com/pub/keith-wade/105/566/8b4"

excerpt_separator: <!--more-->
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
