name: Build and deploy GH Pages

# On every push this script is executed
on:
  push:
    branches:
      - source

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@2
      # Build & deploy
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          # Target branch
          PAGES_BRANCH: master
          # Provide personal access token
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
